### PR TITLE
CSHARP-3085: Re-enable speculative auth integration tests for sharded clusters

### PR DESCRIPTION
**Pull request by vincentkam**
https://evergreen.mongodb.com/version/5ebea4a8d1fe072f3df07246
https://jira.mongodb.org/browse/CSHARP-3085

### CODE REVIEW

**Comment by vincentkam** [comment]
Waiting for EG to go green

**Comment by vincentkam** [comment]
For 4.4 sharded with auth, Net standard 2.0 is green and I've restarted the other two variants.
https://evergreen.mongodb.com/task/dot_net_driver_secure_tests__version~4.4_os~windows_64_topology~sharded_cluster_auth~auth_ssl~ssl_test_netstandard20_patch_faf90213601ab87749bc8611032465cbbe89b21b_5ebea4a8d1fe072f3df07246_20_05_15_14_18_16

Ready for review!

**Review by DmitryLukyanov — APPROVED** [review]
LGTM

**Review by rstam — APPROVED** [review]
LGTM

**Pull request merged**
