### PR TITLE
CSHARP-2620: Change order of frameworks in project files

### PR DESCRIPTION
**Pull request by vincentkam**
https://jira.mongodb.org/browse/CSHARP-2620
https://evergreen.mongodb.com/version/5ced62605623436a81ee34dc
Red in 4.0 is due to https://jira.mongodb.org/browse/CSHARP-2577

### CODE REVIEW

**Comment by vincentkam** [comment]
Ready for review :)

**Review by rstam — APPROVED** [review]
No problem. If we happen to discover any negative consequences of doing this it's easy to reverse.

**Review by DmitryLukyanov — APPROVED** [review]
LGTM

**Comment by vincentkam** [comment]
Merged!

**Pull request merged**
