### PR TITLE
CSHARP-2753: Avoid using readConcern snapshot in sharded transaction tests

### PR DESCRIPTION
**Pull request by vincentkam**
https://jira.mongodb.org/browse/CSHARP-2753
~~https://evergreen.mongodb.com/version/5d8ecafd2a60ed422a628247~~
https://evergreen.mongodb.com/version/5d8f79a37742ae7ca942dde6

### CODE REVIEW

**Comment by rstam** [comment]
The changes look fine, but one test is still failing in Evergreen:

    readConcern snapshot in startTransaction options

in the `transaction-options.json` file.

Perhaps write some code to skip this test against sharded clusters (the only place it's failing). As long as the test runs against other cluster types we're probably covered.

I worry about forgetting to ever start running this test again. Maybe we can check the current date and only skip this test until 2020-01-01 at which time it would start running again. If it still fails then we can extend the date.

**Comment by vincentkam** [comment]
You're right, that test was consistently failing on master and 2.9.x in EG on sharded cluster. Taking a closer look at SPEC-1411, it turns out that I missed one pretty big thing when syncing the changes over:  the `readConcern snapshot in startTransaction options` test was moved to its own separate file that only runs on replicaSets, which would definitely solve the problem we're seeing! I've resynced the tests and submitted new patch builds for both master and 2.9.2: fingers crossed! The date trick is quite interesting 😸 A forcing function to remind us to reinvestigate when EG goes red again... Hopefully with the latest test sync though, EG will simply be green!

**Comment by vincentkam** [comment]
Ready for review!

**Comment by vincentkam** [comment]
(and green in EG) :)

**Review by rstam — APPROVED** [review]

**Comment by vincentkam** [comment]
Rebased and merged to master and v2.9.x branch 😸

**Pull request merged**
