### PR TITLE
CSHARP-3013: Add 4.4 to test matrix

### PR DESCRIPTION
**Pull request by vincentkam**
https://jira.mongodb.org/browse/CSHARP-3013
https://evergreen.mongodb.com/version/5e6fde453e8e862203c27f08

### CODE REVIEW

**Review by jyemin — APPROVED** [review]
LGTM mod a successful patch build.

**Comment by vincentkam** [comment]
4.4 OCSP is purple due to the failpoint not being a no-op on Windows: pinging Shreyas

**Comment by vincentkam** [comment]
Even if it stays purple, I think it should still be fine, as OCSP is still green on latest: if the no-op failpoint doesn't make it into 4.4, then we'll have to revert back to using custom config files for Windows

**Review by DmitryLukyanov — APPROVED** [review]
LGTM

**Comment by vincentkam** [comment]
OCSP is still purple for reasons unrelated to this change, so I'm going to merge this in!

**Pull request merged**
