### PR TITLE
CSHARP-2782: Fix broken testref links in docs

### PR DESCRIPTION
**Pull request by vincentkam**
https://jira.mongodb.org/browse/CSHARP-2782

You should be able to view the non printable character diffs via `git diff gh-pages`
e.g.:
image

See also: https://github.com/vincentkam/mongo-csharp-driver/pull/72

### CODE REVIEW

**Comment by vincentkam** [comment]
Ready for review!

**Comment by vincentkam** [comment]
As discussed offline, I did not regenerate every single set of refdocs from source. The diffs here are the result of  `sed` mixed with some manual tweaking.

**Comment by DmitryLukyanov** [comment]
Not 100% sure what happens here. 
Is it related to `UTF-8` and BOM: https://en.wikipedia.org/wiki/Byte_order_mark ?

I have several questions:
1. Why not all links are broken?
2. Is this change required just because we updated the file manually? I don't recall this requirement when I worked on sites implementation in my previous projects

**Comment by vincentkam** [comment]
> Not 100% sure what happens here.
> Is it related to `UTF-8` and BOM: https://en.wikipedia.org/wiki/Byte_order_mark ?
> 
> I have several questions:
> 
> 1. Why not all links are broken?
> 2. Is this change required just because we updated the file manually? I don't recall this requirement when I worked on sites implementation in my previous projects

This comment has a partial explanation: : https://github.com/vincentkam/mongo-csharp-driver/pull/72#issuecomment-545952209. 

Basically, only the links that were generated with the shortcode `testref` were affected e.g.  https://github.com/mongodb/mongo-csharp-driver/blame/master/Docs/reference/content/reference/driver/crud/linq.md#L14. That shortcode `testref` generated this line: https://github.com/vincentkam/mongo-csharp-driver/pull/73/files#diff-787e0555d6148d14f1ea6140fb7ab070R2420, which if viewed from the CLI, has an invisible BOM character in the link, breaking the link.

**Comment by DmitryLukyanov** [comment]
Ok, LGTM

**Review by DmitryLukyanov — APPROVED** [review]

**Comment by vincentkam** [comment]
Merged!

**Pull request merged**
