### PR TITLE
CSHARP-2766: Fix logo for nuget packages

### PR DESCRIPTION
**Pull request by vincentkam**
https://jira.mongodb.org/browse/CSHARP-2766
Adapted from: https://github.com/mongodb/mongo-csharp-driver/pull/397

Note the lack of NU5048 warnings.
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5048

We did discuss simply asking the docs team to restore the icon at the URL, but this approach also has the advantage of fixing the NU5048 errors.

```
Time Elapsed 00:01:46.18
Finished executing task: Build

========================================
PackageNugetPackages
========================================
Executing task: PackageNugetPackages
Cleaning directory C:/Users/Vincent/driver2/artifacts/packages
Microsoft (R) Build Engine version 16.6.0-preview-20126-02+13cfe7fc5 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Successfully created package 'C:\Users\Vincent\driver2\artifacts\packages\MongoDB.Bson.2.11.0-csharp2766-1.nupkg'.
  Successfully created package 'C:\Users\Vincent\driver2\artifacts\packages\MongoDB.Bson.2.11.0-csharp2766-1.symbols.nupkg'.
Microsoft (R) Build Engine version 16.6.0-preview-20126-02+13cfe7fc5 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Successfully created package 'C:\Users\Vincent\driver2\artifacts\packages\MongoDB.Driver.Core.2.11.0-csharp2766-1.nupkg'.
  Successfully created package 'C:\Users\Vincent\driver2\artifacts\packages\MongoDB.Driver.Core.2.11.0-csharp2766-1.symbols.nupkg'.
Microsoft (R) Build Engine version 16.6.0-preview-20126-02+13cfe7fc5 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Successfully created package 'C:\Users\Vincent\driver2\artifacts\packages\MongoDB.Driver.2.11.0-csharp2766-1.nupkg'.
  Successfully created package 'C:\Users\Vincent\driver2\artifacts\packages\MongoDB.Driver.2.11.0-csharp2766-1.symbols.nupkg'.
Microsoft (R) Build Engine version 16.6.0-preview-20126-02+13cfe7fc5 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Successfully created package 'C:\Users\Vincent\driver2\artifacts\packages\MongoDB.Driver.GridFS.2.11.0-csharp2766-1.nupkg'.
  Successfully created package 'C:\Users\Vincent\driver2\artifacts\packages\MongoDB.Driver.GridFS.2.11.0-csharp2766-1.symbols.nupkg'.
Microsoft (R) Build Engine version 16.6.0-preview-20126-02+13cfe7fc5 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Successfully created package 'C:\Users\Vincent\driver2\artifacts\packages\mongocsharpdriver.2.11.0-csharp2766-1.nupkg'.
  Successfully created package 'C:\Users\Vincent\driver2\artifacts\packages\mongocsharpdriver.2.11.0-csharp2766-1.symbols.nupkg'.
Finished executing task: PackageNugetPackages

========================================
Package
========================================
Executing task: Package
```

### CODE REVIEW

**Comment by vincentkam** [comment]
Ready for review!

**Comment by vincentkam** [comment]
What examining the `nupkg` file shows:
image

**Review by DmitryLukyanov — APPROVED** [review]
LGTM

**Review by rstam — CHANGES_REQUESTED** [review]
I think the icon filename needs to be a little more specific, like `packageicon.png` instead of just `icon.png`

**Comment by vincentkam** [comment]
Renamed! Ready for re-review

**Review by rstam — APPROVED** [review]
LGTM

**Pull request merged**
