### PR TITLE
CSHARP-2790: Docs page dropdown missing versions

### PR DESCRIPTION
**Pull request by vincentkam**
https://jira.mongodb.org/browse/CSHARP-2790

### CODE REVIEW

**Comment by vincentkam** [comment]
Ready for review!

**Review by DmitryLukyanov — APPROVED** [review]

**Review by rstam — APPROVED** [review]
I gather this was just a mistake when deploying to gh-pages?

Because this same file is already correct in master.

**Comment by vincentkam** [comment]
Yep, I neglected to copy this file when deploying to gh-pages. ☹️  I've updated the release guide so I don't forget in the future!

**Comment by vincentkam** [comment]
Merged!

**Pull request merged**
