### PR TITLE
CSHARP-2782: Fix broken testref links in docs

### PR DESCRIPTION
**Pull request by vincentkam**
https://jira.mongodb.org/browse/CSHARP-2782

You should be able to view the non printable character diffs via `git diff master`.

image

See also: https://github.com/vincentkam/mongo-csharp-driver/pull/73

### CODE REVIEW

**Comment by vincentkam** [comment]
Ready for review!

**Comment by vincentkam** [comment]
The shortcode file `testref.html` was saved with a [Byte-Order Mark (BOM)](https://simple.wikipedia.org/wiki/Byte_order_mark). Hugo inserted this BOM into all the links in the documentation that were derived from the this shortcode, resulting in broken links. I've verified with a Hugo preview that removing this BOM from the file fixes the broken links

**Review by rstam — APPROVED** [review]
This is terrible! 

No tool should ever malfunction just because a file has a BOM. A BOM is a perfectly normal thing for there to be at the beginning of a Unicode file.

Hugo... :(

**Comment by vincentkam** [comment]
:( I suppose It's possible that the later versions of Hugo might not suffer from this bug, but IIRC, we're unable to upgrade due to breaking changes?

Rebased, date amended and pushed!

**Pull request closed without merging**
